// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBplt-_8el5gkn9qL3z56azbp_erHMNQ-0',
    appId: '1:97859040124:web:5d49e0df4063b877136af9',
    messagingSenderId: '97859040124',
    projectId: 'mobiledev-34472',
    authDomain: 'mobiledev-34472.firebaseapp.com',
    storageBucket: 'mobiledev-34472.appspot.com',
    measurementId: 'G-4P3CXJJHYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdHvzEsoVbIzs1hzIIYoxv565IMEMWIdU',
    appId: '1:97859040124:android:0695196cc4ae8f1e136af9',
    messagingSenderId: '97859040124',
    projectId: 'mobiledev-34472',
    storageBucket: 'mobiledev-34472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBToNpCTICxXhXiE6uQe7QM_mQUcWVgOOA',
    appId: '1:97859040124:ios:a85b14355c2ed271136af9',
    messagingSenderId: '97859040124',
    projectId: 'mobiledev-34472',
    storageBucket: 'mobiledev-34472.appspot.com',
    iosBundleId: 'com.example.recipeFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBToNpCTICxXhXiE6uQe7QM_mQUcWVgOOA',
    appId: '1:97859040124:ios:9d63dea3b7f472cf136af9',
    messagingSenderId: '97859040124',
    projectId: 'mobiledev-34472',
    storageBucket: 'mobiledev-34472.appspot.com',
    iosBundleId: 'com.example.recipeFlutterApp.RunnerTests',
  );
}
